version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app_network

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge